In [1]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.ndim

2

In [5]:
A.shape

(3, 3)

In [6]:
A.size

9

In [7]:
A[1, 2]

23

In [8]:
A[1][2]

23

In [9]:
A[0][0]

11

In [10]:
A[0][0:2]

array([11, 12])

In [11]:
A[0:2, 2]

array([13, 23])

In [12]:
# addition

X = np.array([[1, 0], [0, 1]]) 
Y = np.array([[2, 1], [1, 2]]) 
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [13]:
# scalae multiplication

Y = np.array([[2, 1], [1, 2]]) 
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [14]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [15]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [16]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [17]:
# dot multiplication

A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [18]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [19]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [20]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

### QUIZ

In [21]:
# Consider the following list a, convert it to Numpy Array.

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
A.size()

<class 'TypeError'>: 'int' object is not callable

In [23]:
A.zize

<class 'AttributeError'>: 'numpy.ndarray' object has no attribute 'zize'

In [24]:
A.size

12

In [25]:
A[0][0:2]

array([1, 2])

In [27]:
# Perform matrix multiplication with the numpy arrays A and B.

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])